//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desguace_Net.DarUnidadTipo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="DarUnidadTipo.DarUnidades")]
    public interface DarUnidades {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/DarUnidades/DarTodasUnidadesRequest", ReplyAction="http://Servicios/DarUnidades/DarTodasUnidadesResponse")]
        Desguace_Net.DarUnidadTipo.DarTodasUnidadesResponse DarTodasUnidades(Desguace_Net.DarUnidadTipo.DarTodasUnidadesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/DarUnidades/DarTodasUnidadesRequest", ReplyAction="http://Servicios/DarUnidades/DarTodasUnidadesResponse")]
        System.Threading.Tasks.Task<Desguace_Net.DarUnidadTipo.DarTodasUnidadesResponse> DarTodasUnidadesAsync(Desguace_Net.DarUnidadTipo.DarTodasUnidadesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/DarUnidades/DarUnidadIdRequest", ReplyAction="http://Servicios/DarUnidades/DarUnidadIdResponse")]
        Desguace_Net.DarUnidadTipo.DarUnidadIdResponse DarUnidadId(Desguace_Net.DarUnidadTipo.DarUnidadIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/DarUnidades/DarUnidadIdRequest", ReplyAction="http://Servicios/DarUnidades/DarUnidadIdResponse")]
        System.Threading.Tasks.Task<Desguace_Net.DarUnidadTipo.DarUnidadIdResponse> DarUnidadIdAsync(Desguace_Net.DarUnidadTipo.DarUnidadIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DarTodasUnidadesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DarTodasUnidades", Namespace="http://Servicios/", Order=0)]
        public Desguace_Net.DarUnidadTipo.DarTodasUnidadesRequestBody Body;
        
        public DarTodasUnidadesRequest() {
        }
        
        public DarTodasUnidadesRequest(Desguace_Net.DarUnidadTipo.DarTodasUnidadesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DarTodasUnidadesRequestBody {
        
        public DarTodasUnidadesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DarTodasUnidadesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DarTodasUnidadesResponse", Namespace="http://Servicios/", Order=0)]
        public Desguace_Net.DarUnidadTipo.DarTodasUnidadesResponseBody Body;
        
        public DarTodasUnidadesResponse() {
        }
        
        public DarTodasUnidadesResponse(Desguace_Net.DarUnidadTipo.DarTodasUnidadesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class DarTodasUnidadesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public DarTodasUnidadesResponseBody() {
        }
        
        public DarTodasUnidadesResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DarUnidadIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DarUnidadId", Namespace="http://Servicios/", Order=0)]
        public Desguace_Net.DarUnidadTipo.DarUnidadIdRequestBody Body;
        
        public DarUnidadIdRequest() {
        }
        
        public DarUnidadIdRequest(Desguace_Net.DarUnidadTipo.DarUnidadIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class DarUnidadIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DarUnidadIdRequestBody() {
        }
        
        public DarUnidadIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DarUnidadIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DarUnidadIdResponse", Namespace="http://Servicios/", Order=0)]
        public Desguace_Net.DarUnidadTipo.DarUnidadIdResponseBody Body;
        
        public DarUnidadIdResponse() {
        }
        
        public DarUnidadIdResponse(Desguace_Net.DarUnidadTipo.DarUnidadIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class DarUnidadIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public DarUnidadIdResponseBody() {
        }
        
        public DarUnidadIdResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DarUnidadesChannel : Desguace_Net.DarUnidadTipo.DarUnidades, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DarUnidadesClient : System.ServiceModel.ClientBase<Desguace_Net.DarUnidadTipo.DarUnidades>, Desguace_Net.DarUnidadTipo.DarUnidades {
        
        public DarUnidadesClient() {
        }
        
        public DarUnidadesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DarUnidadesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DarUnidadesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DarUnidadesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desguace_Net.DarUnidadTipo.DarTodasUnidadesResponse Desguace_Net.DarUnidadTipo.DarUnidades.DarTodasUnidades(Desguace_Net.DarUnidadTipo.DarTodasUnidadesRequest request) {
            return base.Channel.DarTodasUnidades(request);
        }
        
        public string DarTodasUnidades() {
            Desguace_Net.DarUnidadTipo.DarTodasUnidadesRequest inValue = new Desguace_Net.DarUnidadTipo.DarTodasUnidadesRequest();
            inValue.Body = new Desguace_Net.DarUnidadTipo.DarTodasUnidadesRequestBody();
            Desguace_Net.DarUnidadTipo.DarTodasUnidadesResponse retVal = ((Desguace_Net.DarUnidadTipo.DarUnidades)(this)).DarTodasUnidades(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desguace_Net.DarUnidadTipo.DarTodasUnidadesResponse> Desguace_Net.DarUnidadTipo.DarUnidades.DarTodasUnidadesAsync(Desguace_Net.DarUnidadTipo.DarTodasUnidadesRequest request) {
            return base.Channel.DarTodasUnidadesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desguace_Net.DarUnidadTipo.DarTodasUnidadesResponse> DarTodasUnidadesAsync() {
            Desguace_Net.DarUnidadTipo.DarTodasUnidadesRequest inValue = new Desguace_Net.DarUnidadTipo.DarTodasUnidadesRequest();
            inValue.Body = new Desguace_Net.DarUnidadTipo.DarTodasUnidadesRequestBody();
            return ((Desguace_Net.DarUnidadTipo.DarUnidades)(this)).DarTodasUnidadesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desguace_Net.DarUnidadTipo.DarUnidadIdResponse Desguace_Net.DarUnidadTipo.DarUnidades.DarUnidadId(Desguace_Net.DarUnidadTipo.DarUnidadIdRequest request) {
            return base.Channel.DarUnidadId(request);
        }
        
        public string DarUnidadId(int id) {
            Desguace_Net.DarUnidadTipo.DarUnidadIdRequest inValue = new Desguace_Net.DarUnidadTipo.DarUnidadIdRequest();
            inValue.Body = new Desguace_Net.DarUnidadTipo.DarUnidadIdRequestBody();
            inValue.Body.id = id;
            Desguace_Net.DarUnidadTipo.DarUnidadIdResponse retVal = ((Desguace_Net.DarUnidadTipo.DarUnidades)(this)).DarUnidadId(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desguace_Net.DarUnidadTipo.DarUnidadIdResponse> Desguace_Net.DarUnidadTipo.DarUnidades.DarUnidadIdAsync(Desguace_Net.DarUnidadTipo.DarUnidadIdRequest request) {
            return base.Channel.DarUnidadIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desguace_Net.DarUnidadTipo.DarUnidadIdResponse> DarUnidadIdAsync(int id) {
            Desguace_Net.DarUnidadTipo.DarUnidadIdRequest inValue = new Desguace_Net.DarUnidadTipo.DarUnidadIdRequest();
            inValue.Body = new Desguace_Net.DarUnidadTipo.DarUnidadIdRequestBody();
            inValue.Body.id = id;
            return ((Desguace_Net.DarUnidadTipo.DarUnidades)(this)).DarUnidadIdAsync(inValue);
        }
    }
}
