//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desguace_Net.DarNombre {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="DarNombre.DarNombreCliente")]
    public interface DarNombreCliente {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/DarNombreCliente/helloRequest", ReplyAction="http://Servicios/DarNombreCliente/helloResponse")]
        Desguace_Net.DarNombre.helloResponse hello(Desguace_Net.DarNombre.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/DarNombreCliente/helloRequest", ReplyAction="http://Servicios/DarNombreCliente/helloResponse")]
        System.Threading.Tasks.Task<Desguace_Net.DarNombre.helloResponse> helloAsync(Desguace_Net.DarNombre.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cif del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/DarNombreCliente/DarNombreDesguaceRequest", ReplyAction="http://Servicios/DarNombreCliente/DarNombreDesguaceResponse")]
        Desguace_Net.DarNombre.DarNombreDesguaceResponse DarNombreDesguace(Desguace_Net.DarNombre.DarNombreDesguaceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/DarNombreCliente/DarNombreDesguaceRequest", ReplyAction="http://Servicios/DarNombreCliente/DarNombreDesguaceResponse")]
        System.Threading.Tasks.Task<Desguace_Net.DarNombre.DarNombreDesguaceResponse> DarNombreDesguaceAsync(Desguace_Net.DarNombre.DarNombreDesguaceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://Servicios/", Order=0)]
        public Desguace_Net.DarNombre.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(Desguace_Net.DarNombre.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://Servicios/", Order=0)]
        public Desguace_Net.DarNombre.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(Desguace_Net.DarNombre.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DarNombreDesguaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DarNombreDesguace", Namespace="http://Servicios/", Order=0)]
        public Desguace_Net.DarNombre.DarNombreDesguaceRequestBody Body;
        
        public DarNombreDesguaceRequest() {
        }
        
        public DarNombreDesguaceRequest(Desguace_Net.DarNombre.DarNombreDesguaceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class DarNombreDesguaceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cif;
        
        public DarNombreDesguaceRequestBody() {
        }
        
        public DarNombreDesguaceRequestBody(int id, string cif) {
            this.id = id;
            this.cif = cif;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DarNombreDesguaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DarNombreDesguaceResponse", Namespace="http://Servicios/", Order=0)]
        public Desguace_Net.DarNombre.DarNombreDesguaceResponseBody Body;
        
        public DarNombreDesguaceResponse() {
        }
        
        public DarNombreDesguaceResponse(Desguace_Net.DarNombre.DarNombreDesguaceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class DarNombreDesguaceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public DarNombreDesguaceResponseBody() {
        }
        
        public DarNombreDesguaceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DarNombreClienteChannel : Desguace_Net.DarNombre.DarNombreCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DarNombreClienteClient : System.ServiceModel.ClientBase<Desguace_Net.DarNombre.DarNombreCliente>, Desguace_Net.DarNombre.DarNombreCliente {
        
        public DarNombreClienteClient() {
        }
        
        public DarNombreClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DarNombreClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DarNombreClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DarNombreClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desguace_Net.DarNombre.helloResponse Desguace_Net.DarNombre.DarNombreCliente.hello(Desguace_Net.DarNombre.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            Desguace_Net.DarNombre.helloRequest inValue = new Desguace_Net.DarNombre.helloRequest();
            inValue.Body = new Desguace_Net.DarNombre.helloRequestBody();
            inValue.Body.name = name;
            Desguace_Net.DarNombre.helloResponse retVal = ((Desguace_Net.DarNombre.DarNombreCliente)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desguace_Net.DarNombre.helloResponse> Desguace_Net.DarNombre.DarNombreCliente.helloAsync(Desguace_Net.DarNombre.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desguace_Net.DarNombre.helloResponse> helloAsync(string name) {
            Desguace_Net.DarNombre.helloRequest inValue = new Desguace_Net.DarNombre.helloRequest();
            inValue.Body = new Desguace_Net.DarNombre.helloRequestBody();
            inValue.Body.name = name;
            return ((Desguace_Net.DarNombre.DarNombreCliente)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desguace_Net.DarNombre.DarNombreDesguaceResponse Desguace_Net.DarNombre.DarNombreCliente.DarNombreDesguace(Desguace_Net.DarNombre.DarNombreDesguaceRequest request) {
            return base.Channel.DarNombreDesguace(request);
        }
        
        public string DarNombreDesguace(int id, string cif) {
            Desguace_Net.DarNombre.DarNombreDesguaceRequest inValue = new Desguace_Net.DarNombre.DarNombreDesguaceRequest();
            inValue.Body = new Desguace_Net.DarNombre.DarNombreDesguaceRequestBody();
            inValue.Body.id = id;
            inValue.Body.cif = cif;
            Desguace_Net.DarNombre.DarNombreDesguaceResponse retVal = ((Desguace_Net.DarNombre.DarNombreCliente)(this)).DarNombreDesguace(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desguace_Net.DarNombre.DarNombreDesguaceResponse> Desguace_Net.DarNombre.DarNombreCliente.DarNombreDesguaceAsync(Desguace_Net.DarNombre.DarNombreDesguaceRequest request) {
            return base.Channel.DarNombreDesguaceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desguace_Net.DarNombre.DarNombreDesguaceResponse> DarNombreDesguaceAsync(int id, string cif) {
            Desguace_Net.DarNombre.DarNombreDesguaceRequest inValue = new Desguace_Net.DarNombre.DarNombreDesguaceRequest();
            inValue.Body = new Desguace_Net.DarNombre.DarNombreDesguaceRequestBody();
            inValue.Body.id = id;
            inValue.Body.cif = cif;
            return ((Desguace_Net.DarNombre.DarNombreCliente)(this)).DarNombreDesguaceAsync(inValue);
        }
    }
}
