//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 
namespace WsdlService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DarUnidadesPortBinding", Namespace="http://Servicios/")]
    public partial class DarUnidades : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DarUnidadIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback DarTodasUnidadesOperationCompleted;
        
        /// <remarks/>
        public DarUnidades() {
            this.Url = "http://25.162.2.139:8080/Sor_Servicios/DarUnidades";
        }
        
        /// <remarks/>
        public event DarUnidadIdCompletedEventHandler DarUnidadIdCompleted;
        
        /// <remarks/>
        public event DarTodasUnidadesCompletedEventHandler DarTodasUnidadesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DarUnidadId([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id) {
            object[] results = this.Invoke("DarUnidadId", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDarUnidadId(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DarUnidadId", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDarUnidadId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DarUnidadIdAsync(int id) {
            this.DarUnidadIdAsync(id, null);
        }
        
        /// <remarks/>
        public void DarUnidadIdAsync(int id, object userState) {
            if ((this.DarUnidadIdOperationCompleted == null)) {
                this.DarUnidadIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDarUnidadIdOperationCompleted);
            }
            this.InvokeAsync("DarUnidadId", new object[] {
                        id}, this.DarUnidadIdOperationCompleted, userState);
        }
        
        private void OnDarUnidadIdOperationCompleted(object arg) {
            if ((this.DarUnidadIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DarUnidadIdCompleted(this, new DarUnidadIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DarTodasUnidades() {
            object[] results = this.Invoke("DarTodasUnidades", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDarTodasUnidades(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DarTodasUnidades", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDarTodasUnidades(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DarTodasUnidadesAsync() {
            this.DarTodasUnidadesAsync(null);
        }
        
        /// <remarks/>
        public void DarTodasUnidadesAsync(object userState) {
            if ((this.DarTodasUnidadesOperationCompleted == null)) {
                this.DarTodasUnidadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDarTodasUnidadesOperationCompleted);
            }
            this.InvokeAsync("DarTodasUnidades", new object[0], this.DarTodasUnidadesOperationCompleted, userState);
        }
        
        private void OnDarTodasUnidadesOperationCompleted(object arg) {
            if ((this.DarTodasUnidadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DarTodasUnidadesCompleted(this, new DarTodasUnidadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void DarUnidadIdCompletedEventHandler(object sender, DarUnidadIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DarUnidadIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DarUnidadIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void DarTodasUnidadesCompletedEventHandler(object sender, DarTodasUnidadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DarTodasUnidadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DarTodasUnidadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
