//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 
namespace WsdlService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FinishComPortBinding", Namespace="http://Servicios/")]
    public partial class FinishCom : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FinishOperationCompleted;
        
        /// <remarks/>
        public FinishCom() {
            this.Url = "http://25.162.2.139:8080/Sor_Servicios/FinishCom";
        }
        
        /// <remarks/>
        public event FinishCompletedEventHandler FinishCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicios/", ResponseNamespace="http://Servicios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Finish([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id) {
            this.Invoke("Finish", new object[] {
                        id});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFinish(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Finish", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndFinish(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void FinishAsync(int id) {
            this.FinishAsync(id, null);
        }
        
        /// <remarks/>
        public void FinishAsync(int id, object userState) {
            if ((this.FinishOperationCompleted == null)) {
                this.FinishOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFinishOperationCompleted);
            }
            this.InvokeAsync("Finish", new object[] {
                        id}, this.FinishOperationCompleted, userState);
        }
        
        private void OnFinishOperationCompleted(object arg) {
            if ((this.FinishCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FinishCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void FinishCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}
