//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desguace_Net.RegistroDesguace {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="RegistroDesguace.RegistroDesguace")]
    public interface RegistroDesguace {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cif del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/RegistroDesguace/RegistroRequest", ReplyAction="http://Servicios/RegistroDesguace/RegistroResponse")]
        Desguace_Net.RegistroDesguace.RegistroResponse Registro(Desguace_Net.RegistroDesguace.RegistroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/RegistroDesguace/RegistroRequest", ReplyAction="http://Servicios/RegistroDesguace/RegistroResponse")]
        System.Threading.Tasks.Task<Desguace_Net.RegistroDesguace.RegistroResponse> RegistroAsync(Desguace_Net.RegistroDesguace.RegistroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Registro", Namespace="http://Servicios/", Order=0)]
        public Desguace_Net.RegistroDesguace.RegistroRequestBody Body;
        
        public RegistroRequest() {
        }
        
        public RegistroRequest(Desguace_Net.RegistroDesguace.RegistroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RegistroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cif;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email;
        
        public RegistroRequestBody() {
        }
        
        public RegistroRequestBody(string Cif, string Nombre, string Password, string Direccion, string Email) {
            this.Cif = Cif;
            this.Nombre = Nombre;
            this.Password = Password;
            this.Direccion = Direccion;
            this.Email = Email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroResponse", Namespace="http://Servicios/", Order=0)]
        public Desguace_Net.RegistroDesguace.RegistroResponseBody Body;
        
        public RegistroResponse() {
        }
        
        public RegistroResponse(Desguace_Net.RegistroDesguace.RegistroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RegistroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public RegistroResponseBody() {
        }
        
        public RegistroResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistroDesguaceChannel : Desguace_Net.RegistroDesguace.RegistroDesguace, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistroDesguaceClient : System.ServiceModel.ClientBase<Desguace_Net.RegistroDesguace.RegistroDesguace>, Desguace_Net.RegistroDesguace.RegistroDesguace {
        
        public RegistroDesguaceClient() {
        }
        
        public RegistroDesguaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistroDesguaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroDesguaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroDesguaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Desguace_Net.RegistroDesguace.RegistroResponse Desguace_Net.RegistroDesguace.RegistroDesguace.Registro(Desguace_Net.RegistroDesguace.RegistroRequest request) {
            return base.Channel.Registro(request);
        }
        
        public string Registro(string Cif, string Nombre, string Password, string Direccion, string Email) {
            Desguace_Net.RegistroDesguace.RegistroRequest inValue = new Desguace_Net.RegistroDesguace.RegistroRequest();
            inValue.Body = new Desguace_Net.RegistroDesguace.RegistroRequestBody();
            inValue.Body.Cif = Cif;
            inValue.Body.Nombre = Nombre;
            inValue.Body.Password = Password;
            inValue.Body.Direccion = Direccion;
            inValue.Body.Email = Email;
            Desguace_Net.RegistroDesguace.RegistroResponse retVal = ((Desguace_Net.RegistroDesguace.RegistroDesguace)(this)).Registro(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Desguace_Net.RegistroDesguace.RegistroResponse> Desguace_Net.RegistroDesguace.RegistroDesguace.RegistroAsync(Desguace_Net.RegistroDesguace.RegistroRequest request) {
            return base.Channel.RegistroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Desguace_Net.RegistroDesguace.RegistroResponse> RegistroAsync(string Cif, string Nombre, string Password, string Direccion, string Email) {
            Desguace_Net.RegistroDesguace.RegistroRequest inValue = new Desguace_Net.RegistroDesguace.RegistroRequest();
            inValue.Body = new Desguace_Net.RegistroDesguace.RegistroRequestBody();
            inValue.Body.Cif = Cif;
            inValue.Body.Nombre = Nombre;
            inValue.Body.Password = Password;
            inValue.Body.Direccion = Direccion;
            inValue.Body.Email = Email;
            return ((Desguace_Net.RegistroDesguace.RegistroDesguace)(this)).RegistroAsync(inValue);
        }
    }
}
